### ISSUE TITLE
请增加新组件

### ISSUE THREAD

**Issue by xueenda** [adcentury/vue-weui#22]
微信UI 现在有panel tab searchbar
请参照
[http://weui.github.io/weui/](url)

有时间加一下吧 谢谢啦

**Comment by adcentury** [comment]
目前最新版本已经增加了tabbar和navbar，另外两个正在努力实现中，感谢支持

**Comment by xueenda** [comment]
谢谢

**Comment by adcentury** [comment]
恩，最新进度可参见 #19 ，这个issue我就先关掉了
