### ISSUE TITLE
Link-cell 组件的 v-link 指令会覆盖 href 绑定的值

### ISSUE THREAD

**Issue by PeachScript** [adcentury/vue-weui#38]
在使用 `link-cell` 组件的时候，就算只设置 `link` 属性，也不会生成正确的 `href`，因为 `v-link` 指令一旦加上，就会覆写 `href` 属性。

**Comment by adcentury** [comment]
感谢反馈！

 这个我当时也做过权衡，使用`v-if`的问题是会把组件变成片段组件（Fragment Component）

之所以最后采用了现在的方案，是因为如果添加了`v-link`，则我认为你应该是使用了`vue-router`（这是几乎可以确定的事），因此此时应该放弃`href`

**Comment by PeachScript** [comment]
恩，非常抱歉今天才注意到 issues 里面也有回复，所以之前只回复了 Pull Request。你的考虑确实很有道理，反倒是我之前的解决方式显得太过粗鲁了，思考之后我又换了一种方式解决该问题，请看：https://github.com/adcentury/vue-weui/pull/39。

另外个人感觉之前你将这个“权衡”的结果放在组件文档中的话会更加好，这样看文档的人第一眼就能知道 link 和 routerLink 是会产生冲突的 😀

**Comment by adcentury** [comment]
非常感谢你的PR，该问题已经解决，所以我就将issue关闭了哈

**Comment by PeachScript** [comment]
好的，因为手里的项目有使用这个框架，所以希望你能尽快 patch 一个新版本，非常感谢 ~
