### ISSUE TITLE
weui 已经更新到 1.0 版本

### ISSUE THREAD

**Issue by ironmaxtory** [adcentury/vue-weui#51]
weui 已经更新到 1.0 版本
而且CSS命名与之前的版本不兼容
您的代码也需要更新啦~加油，支持

**Comment by adcentury** [comment]
@ironmaxtory 谢谢支持，最近比较忙，元旦有时间的话会做一次比较大的更新

**Comment by proYang** [comment]
你好  可以把我拉到你的项目里面吗？ 我想参与新版本的升级

**Comment by adcentury** [comment]
@proYang 非常感谢！由于我最近时间比较紧张，所以暂时不考虑升级，你可以考虑先通过fork的方式新增自己的升级版本，有任何问题随时联系^_^
