### ISSUE TITLE
我在vue-cli建立的项目引用upload组件，样式class名称与引入css文件不匹配

### ISSUE THREAD

**Issue by glzcc** [adcentury/vue-weui#52]
正确的
![image](https://cloud.githubusercontent.com/assets/11898652/23031718/e91eb158-f4ac-11e6-8bd8-0b8dc60c06bf.png)
我的项目
![image](https://cloud.githubusercontent.com/assets/11898652/23031744/0813bd56-f4ad-11e6-94d6-9a895f6a395d.png)
如何处理下

**Comment by adcentury** [comment]
@itcongaili  是否由于weui版本导致的问题？

**Comment by glzcc** [comment]
可能是吧，我现在不用这个方法写了，谢谢了！
