### ISSUE TITLE
模板解析后类名与weui.css中的不一致

### ISSUE THREAD

**Issue by whirly77cai** [adcentury/vue-weui#54]
以下是摘取字weui.js的一段源码：
`<label :for="id" class="weui_cell weui_check_label">
   <cell-header>
     <input type="checkbox" :name="name" class="weui_check" :id="id" :value="value" vmodel="checked">
    <span class="weui_icon_checked"></span>
   </cell-header>
   <cell-body>{{{label}}}</cell-body>
 </label>`
然而，实际的css文件中
类名是weui-cell, weui-check_label呀

**Comment by DaErDuo** [comment]
我也遇到了同样问题，发现引入 weui.css 或 weui.mini.css 没一点毛用，再一看发现他们的 class 类名，一个是短横线，一个是下划线，简直坑爹

估计 vue-weui 已成弃婴，两年多了作者都没更新

**Comment by adcentury** [comment]
@whirly77cai , @DaErDuo，vue-weui是当时配合weui 0.4.0开发的项目，后面weui进行了较多更新（包括类名的更改），但我由于个人时间原因没能及时更新，如果需要使用最新weui建议选择其他项目

**Comment by meteorlxy** [comment]
@whirly77cai @DaErDuo 正在弄适应weui 1.0+的[vue-weui-components](https://github.com/meteorlxy/vue-weui-components)
